library(vegan)
data(dune)
data(dune.env)
table(dune.env$Management)
bray_distance <- vegdist(dune)
chord_distance <- dist(decostand(dune,"norm"))
library(cluster)
b_cluster <- hclust(bray_distance, method="average")
c_cluster <- hclust(chord_distance, method="average")
par(mfrow=c(1,2))
plot(b_cluster)
plot(c_cluster)
plot(b_cluster)
plot(c_cluster)
